enum ExceptionMessage {
  UNKNOWN_ERROR = 'Unknown error occurred.',
  BAD_CREDENTIALS = 'You have entered an invalid email or password.',
  UNAUTHORIZED_USER = 'Unauthorized user.',
  INVALID_GROUP_NAME = 'Group name is invalid.',
  INVALID_GROUP_PERMISSIONS = 'Group permissions are invalid.',
  INVALID_GROUP_USERS = 'Group users are invalid.',
  INVALID_GROUP_ID = 'Group id is invalid.',
  INVALID_TOKEN = 'Token is invalid.',
  INVALID_URL_HOST = 'URL is invalid. Only courses from Udemy are supported.',
  INVALID_COURSE_VENDOR = 'Course vendor is invalid.',
  INVALID_COURSE_CATEGORY = 'Course category is invalid.',
  UDEMY_SERVER_RETURNED_AN_INVALID_RESPONSE = 'Udemy server returned an invalid response.',
  COURSE_NOT_FOUND = 'Course not found.',
  COURSE_EXIST = 'Course already exists.',
  UNKNOWN_INTERVIEW_NOTE_AUTHOR = 'Unknown interview note author',
  PERMISSION_LACK = 'You do not have permission to access this resource.',
  STORAGE_NOT_FOUND = 'Storage was not found.',
  INVALID_USER_REQUEST = 'User request is invalid.',
  INTERVIEW_EXIST = 'Interview for this category was either passed or is in progress.',
  INTERVIEW_DOES_NOT_EXIST = 'Interview with that ID does not exist.',
  ALREADY_MENTOR_FOR_COURSE = 'You are already a mentor for this course.',
  ALREADY_HAVE_MENTOR_FOR_COURSE = 'You already have a mentor for this course.',
  INVALID_FILE_TYPE = 'The uploaded file has an invalid type.',
  TASK_DOES_NOT_EXIST = 'Task does not exist.',
  TASK_COMPLETED = 'Task is already completed and cannot be updated.',
}
export { ExceptionMessage };
